version: 1

disable_existing_loggers: true

formatters:
    standard:
        format: "[%(asctime)s] [%(levelname)s] [%(filename)s:%(lineno)s] - %(message)s"
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: NOTSET
        formatter: standard
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: NOTSET
        formatter: standard
        filename: ./logs/temp_monitor.log
        maxBytes: 104857600 # 100MB
        backupCount: 4
        encoding: utf8
root:
    level: NOTSET
    handlers: [console, file_handler]
    propogate: no

loggers:
    <module>:
        level: DEBUG
        handlers: []
        propogate: no
